name: cine_loomi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  google_fonts: ^6.2.1
  micro_app_login:
    path: packages/micro_apps/micro_app_login

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

