name: cine_loomi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  google_fonts: ^6.2.1
  flutter_mobx: ^2.3.0
  mobx: ^2.5.0
  go_router: ^14.8.0
  get_it: ^8.0.3



dev_dependencies:
  build_runner: ^2.4.14
  mobx_codegen: ^2.7.0

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

