name: cine_loomi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  google_fonts: ^6.2.1
  
  get: ^4.6.6
  image_picker: ^1.1.2
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  firebase_storage: ^12.4.2
  cloud_firestore: ^5.6.3
  google_sign_in: ^6.2.2
  skeletonizer: ^1.4.3
  palette_generator: ^0.3.3+6
  share_plus: ^10.1.4
  media_kit: ^1.1.11 # Primary package.
  media_kit_video: ^1.2.5 # For video rendering.
  media_kit_libs_video: ^1.0.5 # Native video dependencies.
  video_player: ^2.9.2
  dio: ^5.8.0+1



dev_dependencies:
  flutter_launcher_icons: ^0.14.3

  

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/

  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_package.png"
  adaptive_icon_background: "#131418" 
  background_color_ios: "#131418" 
  min_sdk_android: 21
